version: "3.3"
services:
  java7:
    image: jdk7
    build:
      context: ./jdk7
      dockerfile: Dockerfile
      args:
        buildno: 1
    hostname: java7
    domainname: test.me
    container_name: java7
    command: sleep infinity
    volumes:
    - $HOME/.m2/repository:/root/.m2/repository
    # comment the following line if not running Nexus on your host
    - ./settings.xml:/root/.m2/settings.xml
    - ./dbx-code-grant:/source/dbx-code-grant
    ports:
    - 8090:8090

  redis:
    image: redis
    hostname: redis
    domainname: test.me
    container_name: redis
    volumes:
    - ./redis-data:/data
    ports:
    - 6379:6379
